export default {
    capabilities: state => state.capabilities,
    council: state => state.council,
    currentClient: state => state.currentClient,
    currentEvent: state => state.currentEvent,
    currentGuard: state => state.currentGuard,
    currentMeeting: state => state.currentMeeting,
    currentPerson: state => state.currentPerson,
    currentProfile: state => state.currentProfile,
    currentResource: state => state.currentResource,
    currentShift: state => state.currentShift,
    currentSurvey: state => state.currentSurvey,
    currentUnit: state => state.currentUnit,
    currentUser: state => state.currentUser,
    currentVenue: state => state.currentVenue,
    currentWorkplace: state => state.currentWorkplace,
    inProgress: state => !!state.pendingRequests,
    isAuthenticated: state => !!state.currentUser,
    menu: state => state.menu,
    personRoles: state => state.personRoles,
    polls: state => state.polls,
    systemParams: state => state.systemParams,
    userPollsReady: state => state.userPollsReady,
}
