export default {
    capabilities: [],
    council: null,
    currentClient: null,
    currentEvent: null,
    currentGuard: null,
    currentMeeting: null,
    currentMenuItems: [],
    currentPerson: null,
    currentProfile: null,
    currentResource: null,
    currentShift: null,
    currentUnit: null,
    currentUser: null,
    currentVenue: null,
    currentWorkplace: null,
    menu: [],
    menuItems: [],
    pendingRequests: 0,
    personRoles: [],
    polls: [],
    systemParams: null,
    userPollsReady: [], // Encuestas que el usuario ya voto
}
